### ISSUE TITLE
BIOS Version

### ISSUE THREAD

**Issue by ChrisKader** [PowerBall253/AN515-54-Hackintosh#12]
What BIOS version are you running (one in the screenshots that shows trackpad options) and are there any modifications outside of the CFG changes?

**Comment by PowerBall253** [comment]
Latest BIOS version, only changes are the ones explained in the README (AHCI mode for SATA, disable Fast Boot and Secure Boot).

**Comment by brunoanc** [comment]
Latest BIOS version, only changes are the ones explained in the README (AHCI mode for SATA, disable Fast Boot and Secure Boot).
