### ISSUE TITLE
BIOS Blackscreen

### ISSUE THREAD

**Issue by Italo-Nogueira** [PowerBall253/AN515-54-Hackintosh#2]
How open BIOS? When I reboot with F2, I get a fucking Blackscreen with "_". 
![IMG_20211119_193026719 MP](https://user-images.githubusercontent.com/85213457/142699624-7948de9c-c885-4db3-b66f-6c76006cfdb4.jpg)
Did u see that?

**Comment by PowerBall253** [comment]
Only solution I've found for this was resetting the BIOS by holding the power button for around 15 seconds while the laptop is shut down, however, this will reset all your BIOS settings and entries so you'll have to reconfigure it.

**Comment by Italo-Nogueira** [comment]
Ok, I will try it. This only do it when I've a pendrive plugged, if I remove pendrive, I can open BIOS normally.  Bluetooth is broked for me too 😪 and config.plist dont open in ProperTree =/

**Comment by PowerBall253** [comment]
Some pendrives cause that, don't reset the BIOS if the issue is just with the pendrive. What error does ProperTree give you? Which macOS version are you trying to run?
