### ISSUE TITLE
Fan Control

### ISSUE THREAD

**Issue by itsmeshibintmz** [PowerBall253/AN515-54-Hackintosh#5]
The fan is running at 100% all time. Any kext files to make it control? It shows reset SMC when opening MacOS Fan Control.

**Comment by PowerBall253** [comment]
I haven't been able to control fans manually through macOS Fan Control or other apps, but the system still manages them automatically. Are they running at 100% even when idle?

**Comment by itsmeshibintmz** [comment]
Yeah, it's running on 100% most of the time even when a few apps open or even idle too. Temperatures and Resource usages are normal.

**Comment by PowerBall253** [comment]
Are you running the Big Sur or the Monterey EFI?

**Comment by itsmeshibintmz** [comment]
> Hello, I've been facing the same problem lately with the fan control, is there any solution for it yet? thanks!

no fixes yet, the system adjusts it automatically. we can't control it.
