### ISSUE TITLE
Your Updated EFI is not Booting tried 2 times with no success 

### ISSUE THREAD

**Issue by anuppatell** [PowerBall253/AN515-54-Hackintosh#6]
When I try to boot the pendrive its just show some code and it restarts

**Comment by PowerBall253** [comment]
Did a previous version work for you?

**Comment by anuppatell** [comment]
> Did a previous version work for you?

Yes previous version worked

**Comment by PowerBall253** [comment]
Are you using the Monterey or the Big Sur one? Which macOS version are you running?

**Comment by anuppatell** [comment]
> Are you using the Monterey or the Big Sur one? Which macOS version are you running?

Big Sur

**Comment by PowerBall253** [comment]
What text appears on the screen before it restarts?

**Comment by anuppatell** [comment]
> What text appears on the screen before it restarts?

It's was unreadable because it's just come and gone in second

**Comment by anuppatell** [comment]
So Tried again with different pendrive now its booted but stuck at apple logo

**Comment by PowerBall253** [comment]
How much did you wait before shutting it off?

**Comment by anuppatell** [comment]
Now its booted and perfectly Installed on my Nitro 5 now thankyou but the only problem I have is that fan is running at max all the time
