### ISSUE TITLE
Why is the trackpad not working..?

### ISSUE THREAD

**Issue by VaibhavKukreti-Kathud** [PowerBall253/AN515-54-Hackintosh#8]
The readme file has it.... It's working but I don't think so i installed macos yesterday only with your EFI and the trackpad isn't working I can confirm.

**Comment by VaibhavKukreti-Kathud** [comment]
@PowerBall253

**Comment by PowerBall253** [comment]
Are you using the Monterey or Big Sur EFI?

**Comment by VaibhavKukreti-Kathud** [comment]
using the monterey EFI...

**Comment by VaibhavKukreti-Kathud** [comment]
and about the touchpad mode.... I don't have that option in the BIOS?

**Comment by PowerBall253** [comment]
> and about the touchpad mode.... I don't have that option in the BIOS?

![image](https://user-images.githubusercontent.com/77066815/154694012-f5c63d8c-cce3-425d-88bf-1843e0a7ec03.png)

Do you not have an option like the "Touchpad" one there?

**Comment by VaibhavKukreti-Kathud** [comment]
nope

**Comment by VaibhavKukreti-Kathud** [comment]
I have acer nitro 5 an515-51

**Comment by PowerBall253** [comment]
Can you send me a pic of the bios options?

**Comment by VaibhavKukreti-Kathud** [comment]
![image](https://user-images.githubusercontent.com/67002144/154704772-10768c1f-b6f4-4881-97d9-ac27894182b7.png)

**Comment by PowerBall253** [comment]
Maybe check if there's any update available for your BIOS?

**Comment by VaibhavKukreti-Kathud** [comment]
I looked up for updates didn't find any new ones
